### PR TITLE
Added parameter and tests for the number of context lines to comment on

### LINKED ISSUE #15: Violation comments on context lines around differences
Some tools create quite a lot of warnings and can uncover problems that went unnoticed for a long time. In our case, we started using CheckStyle and it has quite a lot to comment about our code, almost on every line or so. This led us to notice that using commentOnlyChangedContent set to true, we still got comments on lines that were not actually touched but were in the immediate vicinity of changes.

Digging into the problem, we noticed that GitLab provides up to +/- 3 more lines of context around the actual changes. If those lines contain problems, there will be comments left for them in the merge request. Fixing those just takes the problem one step further as now the difference will contain the previous context lines, now changed content, plus another +/-3 more lines of context. Context lines coupled with a verbose checking tool tend to make the commentOnlyChangedContent property kind of useless. In the end you need to update the whole file anyways. 

I have a PR **almost** ready for this, the question I have is if we:

1. add an option along commentOnlyChangedContent, say commentOnlyChangedLines or ignoreContextLines, that we can use to keep previous behavior as is and make it possible to restrict the commented lines even further for the ones that want it
2. just change the current behavior of commentOnlyChangedContent to ignore context lines aroud differences as well. 

I'd personally go for option 2., not just because it is simpler (not in implementation but in rolling out, as you don't have 4 other projects to update: jenkins, maven, gradle and cmdline) but also because that is probably the reason why someone uses commentOnlyChangedContent in the first place. 

Let me know what you think...

### PR DESCRIPTION
**Pull request by ateglas**
Closes #15 

The changes are as follow:
1. Implemented commentOnlyChangedContentContext with similar effects to the Bitbucket implementation. 
2. Added tests to show the new behavior
3. Refactored older tests to remove some of the noise and make it clearer as to what we are verifying

Let me know if this is close to what you had in mind or we need to tweak it a bit.

### CODE REVIEW

**Comment by tomasbjerre** [comment]
Thanks! This library is now released, no plugins/tools released yet, will you work on that?

**Comment by ateglas** [comment]
Yes, I can add the parameter to the plugins. I think the updates need to be
for:

https://github.com/jenkinsci/violation-comments-to-gitlab-plugin
https://github.com/tomasbjerre/violation-comments-to-gitlab-gradle-plugin
https://github.com/tomasbjerre/violation-comments-to-gitlab-gradle-plugin
https://github.com/tomasbjerre/violation-comments-to-gitlab-command-line

Anything I'm missing?

**Comment by tomasbjerre** [comment]
Thanks!

You mentioned the gradle plugin twice but you probably mean the gradle and maven plugin. No nothing missing.

**Comment by ateglas** [comment]
Yup, gradle and maven. Thanks for confirming, I will raise the PRs later
today.

**Pull request merged**
